---
title: "Example Case Study"
output: html_document
---

```{r}
library(tidyverse)
library(ggridges)
library(leaflet)
library(p8105.datasets)

data(nyc_airbnb)

nyc_airbnb = 
  nyc_airbnb %>% 
  rename(borough = neighbourhood_group) %>%  
  mutate(stars = review_scores_location / 2)

view(nyc_airbnb)
```

## Understanding Variables 

```{r}
# View(nyc_airbnb)
str(nyc_airbnb) 

nyc_airbnb %>%
  count(room_type)

view(nyc_airbnb)

nyc_airbnb %>%
  count(neighbourhood)
variable.names(nyc_airbnb)
```

## Questions about the dataset brainstorm 
      - Where are AirBNBs most expensive in NYC?

## Do some EDA

```{r}
nyc_airbnb %>%  
  count(borough)
```

```{r}
nyc_airbnb %>% 
  group_by(borough, room_type) %>% 
  summarize(mean_price = mean(price)) %>% 
  pivot_wider(
      names_from = room_type,
      values_from = mean_price
  )
```

To do a comparison in median price 

```{r}
nyc_airbnb %>% 
  group_by(borough, room_type) %>% 
  summarize(median_price = median(price)) %>% 
  pivot_wider(
      names_from = room_type,
      values_from = median_price
  )
```

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = price)) +
  geom_histogram() +
  facet_grid(borough ~ room_type)
```

```{r}
nyc_airbnb %>% 
  filter(price < 1000, room_type == "Entire home/apt") %>% 
  ggplot(aes(x = price)) +
  geom_histogram() +
  facet_grid(. ~ borough)
```

```{r}
nyc_airbnb %>% 
    filter(price < 1000, 
           room_type == "Entire home/apt",
           borough == "Manhattan") %>% 
  group_by(neighbourhood) %>% 
  summarize(
    n_apt = n(),
    mean_price = mean(price)) %>% 
  arrange(desc(mean_price))

```

```{r}
nyc_airbnb %>% 
  filter(
    price < 1000,
    room_type == "Entire home/apt",
    borough == "Manhattan") %>% 
      mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
      ggplot(aes(x = price, y = neighbourhood)) +
    geom_density_ridges(
  )
```

## Trying to make MAPS!

```{r}
nyc_airbnb %>% 
  filter(
    price < 1000,
    room_type == "Entire home/apt",
    borough == "Manhattan") %>% 
  ggplot(aes(x = lat, y = long, color = price)) + 
  geom_point()
```

Trying another map entirely:

```{r}
nyc_airbnb %>% 
  filter(
    price < 1000,
    room_type == "Entire home/apt",
    borough == "Manhattan") %>% 
  sample_n(500) %>% 
  leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(~lat, ~long, radius = .5)  
  
```

